all:
	(cd basicmath; make all)
	(cd bitcount; make all)
	(cd qsort; make all)
	(cd susan; make all)

clean:
	(cd basicmath; make clean)
	(cd bitcount; make clean)
	(cd qsort; make clean)
	(cd susan; make clean)
